name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: build
      run: | 
        cd sources
        dotnet restore
        dotnet build --configuration Release --no-restore

    - name: test
      run: | 
        cd sources
        cd test_tabla
        dotnet test --no-restore --verbosity normal

    - name: publish    
      run: |   
        cd sources
        cd sah_web
        dotnet publish --configuration Release  -r win-x64 --self-contained -o sahwebOutput -p:PublishSingleFile=true -p:PublishTrimmed=true
        ls -lh

    - uses: actions/upload-artifact@v2
      with:
        name: proiectSah
        path: sources/sah_web/sahwebOutput